--TABLE FOR AVATAR MASTERDATA
CREATE TABLE IF NOT EXISTS AVATAR(
ID INT NOT NULL,
NAME VARCHAR(200) NOT NULL
IMG VARCHAR(200) NOT NULL)
;

--TABLE FOR CARDS MASTERDATA
CREATE TABLE IF NOT EXISTS CARDS(
ID INT NOT NULL,
NAME  VARCHAR(200) NOT NULL,
IMG VARCHAR(200) NOT NULL,
ISVISIBLE VARCHAR(200) NOT NULL)
;

--TABLE FOR USERS WITH UNIQUE EMAIL
CREATE TABLE IF NOT EXISTS USERS (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(200) NOT NULL,
  EMAIL VARCHAR(200) NOT NULL,
  AVATAR INT NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE users_email_uk (EMAIL))
;

--TABLE FOR SCORES 
CREATE TABLE IF NOT EXISTS SCORES (
  ID INT NOT NULL AUTO_INCREMENT,
  NUMFAILS INT NOT NULL,  
  USERS_ID INT NOT NULL,
  
 PRIMARY KEY (ID),
  CONSTRAINT FK_SCORES_USERS
    FOREIGN KEY (USERS_ID)
    REFERENCES USERS (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;