--TABLE FOR AVATAR MASTERDATA
CREATE TABLE IF NOT EXISTS AVATARS(
ID INT NOT NULL,
NAME VARCHAR(200) NOT NULL
IMG VARCHAR(200) NOT NULL)
;

--TABLE FOR CARDS MASTERDATA
CREATE TABLE IF NOT EXISTS CARDS(
ID INT NOT NULL,
NAME  VARCHAR(200) NOT NULL,
IMG VARCHAR(200) NOT NULL,
ISVISIBLE VARCHAR(200) NOT NULL)
;

--TABLE FOR USERS WITH UNIQUE EMAIL
CREATE TABLE IF NOT EXISTS USERS (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(200) NOT NULL,
  LASTNAME VARCHAR(200) NOT NULL,
  EMAIL VARCHAR(200) NOT NULL,
  AVATAR INT NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE users_email_uk (EMAIL))
;

--TABLE FOR SCORES 
CREATE TABLE IF NOT EXISTS SCORES (
  ID INT NOT NULL AUTO_INCREMENT,
  NUMFAILS INT NOT NULL,  
  EMAIL INT NOT NULL,  
 PRIMARY KEY (ID)  
;